version: 2
jobs:
  build:
    docker:
      - image: golang:1.14-alpine
    working_directory: /go/src/github.com/TicketsBot/whitelabelpremiumcheckdaemon

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run:
          name: Install GCC & musl-dev
          command: apk add gcc musl-dev

      - run:
          name: Build daemon
          command: go build -o main cmd/premiumcheckdaemon/main.go

      - store_artifacts:
          path: /go/src/github.com/TicketsBot/whitelabelpremiumcheckdaemon/main
          destination: main
